### ISSUE TITLE
does not work?

### ISSUE THREAD

**Issue by ripandtearr** [tylerbrockett/reddit-bot-buildapcsales#18]
re: title, the bot does not appear to do anything for me

"stats"/"subs" produces a reply, but my subscription (a nonspecific "subscribe buildapcsales") has yielded zero PMs in 24 hours

**Comment by ripandtearr** [comment]
hmm, nevermind, it's working now

**Comment by tylerbrockett** [comment]
@ripandtearr, sorry about that, and thanks for bringing it to my attention. Two nights ago I was playing around with catching a specific UserInvalid error (deleted account), which caught it fine, but it introduced another exception. 😞

Anyway, I think that should now be resolved as well, and the bot is running through the rounds.
