### ISSUE TITLE
I'm not sure it's working right now.

### ISSUE THREAD

**Issue by Windsooon** [tylerbrockett/reddit-bot-buildapcsales#5]
I used to get alert after I subscribe subreddit page, but now I can't get any alert message after I post the correct post, any idea?

**Comment by tylerbrockett** [comment]
Can you send me the exact message you sent to the bot? And can you screenshot how it looks in your subscription list?

**Comment by tylerbrockett** [comment]
@Windsooon Can you send me the exact message you sent to the bot?

**Comment by Windsooon** [comment]
Hi, What I send is 
    
    subscribe -title YouTube, website, resource -subreddit Basketball

and I also try 

    subscribe -title youtube, website, resource -subreddit Boxing

 The title is not case sensitive right?  I got the message from the bot, But after I post, no message alert.

**Comment by tylerbrockett** [comment]
@Windsooon That is the correct format for the message, and you're correct, it is not case sensitive.

The subscription you sent the bot would have it look for "YouTube", "website", and " resource" in the title (order doesn't matter). All would need to be in the title to constitute a match. Is this what your intentions were?

There is a different way to subscribe if you want an alert if only **_one_** of those terms shows up in the title, if that's what your intention was.

**Comment by Windsooon** [comment]
Yes, I used to get alert message after I set up, but not anymore. I also tried today, I sent the message to the bot.

    subscribe -title youtube, website, resource -subreddit nfl

After that I post a post on https://www.reddit.com/r/nfl/,   the link is https://www.reddit.com/r/nfl/comments/745jkd/youtube_channels_about_nfl/, but I haven't got any message from the bot

**Comment by tylerbrockett** [comment]
@Windsooon That post doesn't match against the message you sent the bot. The way you sent the subscription, all three words (YouTube, website, and resource) must be in the title. The post only has "YouTube" and "website" but not "resource"

**Comment by Windsooon** [comment]
Thanks, I should read the docs more carefully!

**Comment by tylerbrockett** [comment]
@Windsooon Cool, I'm gonna close the bug then. If you have any questions about how to set up a subscription for what you want, feel free to send me a message on Reddit!
