### ISSUE TITLE
New feature needed

### ISSUE THREAD

**Issue by Windsooon** [tylerbrockett/reddit-bot-buildapcsales#6]
I want the bot can ignore the title just a link that links to another url.  For example, this one https://www.reddit.com/r/Cricket/comments/7ceno2/psl_pakistan_super_league_3_draft_2018_live/

Any possible to let title ignore URL like:

`subscribe -title cats -ignore-title-link -subreddit videos`

to ignore the post that just a link even though it contains cats in its title?

**Comment by tylerbrockett** [comment]
This might be achievable with something like

`subscribe -title cats --ignore-body https:// --subreddit videos`

Try playing around with the `--ignore-body` parameter, which should also handle link posts.
