### ISSUE TITLE
Post title not clickable on reddit mobile app

### ISSUE THREAD

**Issue by tmchow** [tylerbrockett/reddit-bot-buildapcsales#7]
When getting alert not messages for matching posts, the post title isn’t clickable through the reddit mobile app. This makes the alert useless on the Reddit mobile app since there is no way to get to the matching post.

**Comment by tylerbrockett** [comment]
@tmchow is this the official Reddit mobile app? What platform are you on?

**Comment by tylerbrockett** [comment]
Closing as there has been no update

**Comment by tmchow** [comment]
@tylerbrockett This is on official reddit mobile app

**Comment by tylerbrockett** [comment]
@tmchow what platform is this on, Android or iOS?

I just installed the official Reddit app on Android and it seems to be working as expected.

**Comment by tmchow** [comment]
@tylerbrockett it’s on iOS on the officia reddit mobile app. It doesn’t happen to all msgs just some. I cannot pinpoint why. It may be a bug in Reddit app since the emails seem to be clickable in Apollo and narwhal.
